# =============================================================================
# Media Monitoring Platform - Windows setup
# اعداد منصة رصد وتحليل المنصات الاعلامية
#
# Run from the platform folder:   .\setup.bat
# =============================================================================

$ErrorActionPreference = 'Stop'
$envPath = Join-Path $PSScriptRoot '.env'

function Write-Q([int]$n, [int]$total, [string]$titleEn, [string]$titleAr, [string]$hintAr) {
  Write-Host ''
  Write-Host "  [$n/$total] $titleEn" -ForegroundColor Cyan
  Write-Host "         $titleAr" -ForegroundColor Gray
  if ($hintAr) { Write-Host "         $hintAr" -ForegroundColor DarkGray }
}

function Read-Value([int]$n, [int]$total, [string]$titleEn, [string]$titleAr, [string]$hintAr,
                    [int]$minLength, [string]$defaultValue) {
  while ($true) {
    Write-Q $n $total $titleEn $titleAr $hintAr
    $value = (Read-Host '  >').Trim()
    if ([string]::IsNullOrEmpty($value) -and $defaultValue) { return $defaultValue }
    if ($value.Length -ge $minLength -and $value -notmatch '["#]') { return $value }
    Write-Host "         ! too short, or contains a forbidden character (double quote or hash)" -ForegroundColor Yellow
    Write-Host "         ! قصير جدا او يحتوي محرفا ممنوعا" -ForegroundColor Yellow
  }
}

Write-Host ''
Write-Host '  ============================================' -ForegroundColor Cyan
Write-Host '   Media Monitoring Platform - Setup' -ForegroundColor Cyan
Write-Host '   اعداد منصة رصد وتحليل المنصات الاعلامية' -ForegroundColor Cyan
Write-Host '  ============================================' -ForegroundColor Cyan

if (Test-Path $envPath) {
  Write-Host ''
  Write-Host '  A .env file already exists.' -ForegroundColor Yellow
  Write-Host '  يوجد ملف اعدادات بالفعل' -ForegroundColor Yellow
  Write-Host '  Type  y  to replace it, or  n  to cancel.' -ForegroundColor Yellow
  $answer = (Read-Host '  > (y/n)').Trim().ToLower()
  if ($answer -ne 'y') {
    Write-Host ''
    Write-Host '  Cancelled. Nothing was changed.' -ForegroundColor Yellow
    Write-Host '  الغي الاعداد ولم يتغير شيء' -ForegroundColor Yellow
    exit 0
  }
}

Write-Host ''
Write-Host '  Answer 6 questions. Use Latin letters and digits only.' -ForegroundColor Gray
Write-Host '  اجب عن 6 اسئلة بحروف لاتينية وارقام فقط' -ForegroundColor Gray

$dbPassword = Read-Value 1 6 'Database password' 'كلمة مرور قاعدة البيانات' 'example: MonitorDb2026' 8 ''
$ownerEmail = Read-Value 2 6 'Your email (used to sign in)' 'بريدك الالكتروني للدخول' 'example: name@example.com' 5 ''
$ownerName  = Read-Value 3 6 'Your name in Latin letters' 'اسمك بحروف لاتينية' 'you can switch it to Arabic inside the app later' 2 ''
$ownerPass  = Read-Value 4 6 'Your login password' 'كلمة مرور دخولك' 'at least 10 characters, must contain a digit' 10 ''
$apifyToken = Read-Value 5 6 'Apify token (press Enter to skip)' 'رمز ابيفاي - اضغط Enter لتخطيه' 'you can add it later in the .env file' 0 'SKIP'
$appPort    = Read-Value 6 6 'Port on your computer (press Enter for 3000)' 'المنفذ على جهازك' 'use another port such as 3100 if 3000 is busy' 0 '3000'

if ($apifyToken -eq 'SKIP') { $apifyToken = '' }

$bytes = New-Object byte[] 48
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$sessionSecret = [Convert]::ToBase64String($bytes)

$content = @"
# Generated by setup.ps1 - contains secrets, do not share
POSTGRES_USER="monitor"
POSTGRES_DB="monitoring"
POSTGRES_PASSWORD="$dbPassword"
DATABASE_URL="postgresql://monitor:$dbPassword@localhost:5432/monitoring?schema=public"
REDIS_URL="redis://localhost:6379"
SESSION_SECRET="$sessionSecret"
SESSION_TTL_DAYS="7"
APP_PORT="$appPort"
APP_URL="http://localhost:$appPort"
APIFY_TOKEN="$apifyToken"
APIFY_API_BASE="https://api.apify.com/v2"
APIFY_MAX_ITEMS_HARD_CAP="1000"
APIFY_RUN_TIMEOUT_SECONDS="900"
SEED_OWNER_EMAIL="$ownerEmail"
SEED_OWNER_NAME="$ownerName"
SEED_OWNER_PASSWORD="$ownerPass"
NODE_ENV="development"
"@

[System.IO.File]::WriteAllText($envPath, $content, (New-Object System.Text.UTF8Encoding $false))

Write-Host ''
Write-Host '  ============================================' -ForegroundColor Green
Write-Host '   .env created successfully' -ForegroundColor Green
Write-Host '   تم انشاء ملف الاعدادات بنجاح' -ForegroundColor Green
Write-Host '  ============================================' -ForegroundColor Green
if ([string]::IsNullOrEmpty($apifyToken)) {
  Write-Host ''
  Write-Host '  Note: Apify token is empty - the site runs but extraction stays off.' -ForegroundColor Yellow
  Write-Host '  رمز ابيفاي فارغ - الموقع يعمل لكن الاستخراج معطل' -ForegroundColor Yellow
}
Write-Host ''
Write-Host '  Next step / الخطوة التالية:' -ForegroundColor Cyan
Write-Host '      docker compose up -d --build'
Write-Host ''
Write-Host "  Then open / ثم افتح:   http://localhost:$appPort"
Write-Host "  Sign in with / سجل الدخول بـ:   $ownerEmail"
Write-Host ''
