#!/usr/bin/env bash
# =============================================================================
# Media Monitoring Platform - macOS / Linux setup
# اعداد منصة رصد وتحليل المنصات الاعلامية
#
# Run from the platform folder:   bash setup.sh
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"
ENV_PATH=".env"

C_CYAN=$'\033[36m'; C_GRAY=$'\033[90m'; C_YELLOW=$'\033[33m'; C_GREEN=$'\033[32m'; C_OFF=$'\033[0m'

echo
echo "${C_CYAN}  ============================================${C_OFF}"
echo "${C_CYAN}   Media Monitoring Platform - Setup${C_OFF}"
echo "${C_CYAN}   اعداد منصة رصد وتحليل المنصات الاعلامية${C_OFF}"
echo "${C_CYAN}  ============================================${C_OFF}"

if [ -f "$ENV_PATH" ]; then
  echo
  echo "${C_YELLOW}  A .env file already exists.${C_OFF}"
  echo "${C_YELLOW}  يوجد ملف اعدادات بالفعل${C_OFF}"
  echo "${C_YELLOW}  Type  y  to replace it, or  n  to cancel.${C_OFF}"
  read -r -p "  > (y/n) " answer
  if [ "${answer,,}" != "y" ]; then
    echo
    echo "${C_YELLOW}  Cancelled. Nothing was changed.${C_OFF}"
    exit 0
  fi
fi

echo
echo "${C_GRAY}  Answer 6 questions. Use Latin letters and digits only.${C_OFF}"
echo "${C_GRAY}  اجب عن 6 اسئلة بحروف لاتينية وارقام فقط${C_OFF}"

# read_value <n> <total> <title_en> <title_ar> <hint> <min_len> <default>
read_value() {
  local n="$1" total="$2" en="$3" ar="$4" hint="$5" min="$6" def="${7:-}" value=""
  while true; do
    echo >&2
    echo "${C_CYAN}  [$n/$total] $en${C_OFF}" >&2
    echo "${C_GRAY}         $ar${C_OFF}" >&2
    [ -n "$hint" ] && echo "${C_GRAY}         $hint${C_OFF}" >&2
    read -r -p "  > " value
    if [ -z "$value" ] && [ -n "$def" ]; then printf '%s' "$def"; return; fi
    if [ "${#value}" -ge "$min" ] && [[ "$value" != *'"'* ]] && [[ "$value" != *'#'* ]]; then
      printf '%s' "$value"; return
    fi
    echo "${C_YELLOW}         ! too short, or contains a forbidden character${C_OFF}" >&2
  done
}

DB_PASSWORD=$(read_value 1 6 "Database password" "كلمة مرور قاعدة البيانات" "example: MonitorDb2026" 8)
OWNER_EMAIL=$(read_value 2 6 "Your email (used to sign in)" "بريدك الالكتروني للدخول" "example: name@example.com" 5)
OWNER_NAME=$(read_value 3 6 "Your name in Latin letters" "اسمك بحروف لاتينية" "you can switch it to Arabic inside the app later" 2)
OWNER_PASS=$(read_value 4 6 "Your login password" "كلمة مرور دخولك" "at least 10 characters, must contain a digit" 10)
APIFY_TOKEN=$(read_value 5 6 "Apify token (press Enter to skip)" "رمز ابيفاي - اضغط Enter لتخطيه" "you can add it later in the .env file" 0 "SKIP")
APP_PORT=$(read_value 6 6 "Port on your computer (press Enter for 3000)" "المنفذ على جهازك" "use another port such as 3100 if 3000 is busy" 0 "3000")

[ "$APIFY_TOKEN" = "SKIP" ] && APIFY_TOKEN=""

SESSION_SECRET=$(openssl rand -base64 48 2>/dev/null || head -c 48 /dev/urandom | base64 | tr -d '\n')

cat > "$ENV_PATH" <<EOF
# Generated by setup.sh - contains secrets, do not share
POSTGRES_USER="monitor"
POSTGRES_DB="monitoring"
POSTGRES_PASSWORD="$DB_PASSWORD"
POSTGRES_PORT="55432"
REDIS_PORT="6380"
DATABASE_URL="postgresql://monitor:$DB_PASSWORD@localhost:55432/monitoring?schema=public"
REDIS_URL="redis://localhost:6380"
SESSION_SECRET="$SESSION_SECRET"
SESSION_TTL_DAYS="7"
APP_PORT="$APP_PORT"
APP_URL="http://localhost:$APP_PORT"
APIFY_TOKEN="$APIFY_TOKEN"
APIFY_API_BASE="https://api.apify.com/v2"
APIFY_MAX_ITEMS_HARD_CAP="1000"
APIFY_RUN_TIMEOUT_SECONDS="900"
SEED_OWNER_EMAIL="$OWNER_EMAIL"
SEED_OWNER_NAME="$OWNER_NAME"
SEED_OWNER_PASSWORD="$OWNER_PASS"
NODE_ENV="development"
EOF

chmod 600 "$ENV_PATH"

echo
echo "${C_GREEN}  ============================================${C_OFF}"
echo "${C_GREEN}   .env created successfully${C_OFF}"
echo "${C_GREEN}   تم انشاء ملف الاعدادات بنجاح${C_OFF}"
echo "${C_GREEN}  ============================================${C_OFF}"
[ -z "$APIFY_TOKEN" ] && echo "${C_YELLOW}  Note: Apify token is empty - extraction stays off until you add it.${C_OFF}"
echo
echo "${C_CYAN}  Next step / الخطوة التالية:${C_OFF}"
echo "      docker compose up -d --build"
echo
echo "  Then open / ثم افتح:   http://localhost:$APP_PORT"
echo "  Sign in with / سجل الدخول بـ:   $OWNER_EMAIL"
echo
